# Spring Service Configuration
server:
  port: 8000
  tomcat:
    uri-encoding: utf-8

# Spring MVC Configuration
spring:
  application:
    name: discover-eureka
#  jpa:
#    database: MYSQL
#    hibernate:
#      ddl-auto: create-drop
#      show-sql: true
#  datasource:
#    username: root
#    password:
#    url: jdbc:mysql://localhost:3306/db_book?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8
#    driverClassName: com.mysql.jdbc.Driver


# Eureka Server Configuration

eureka: 
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: 'http://${eureka.instance.hostname}:${server.port}/eureka/'